### ISSUE TITLE
deepBGC incorrect result directory

### ISSUE THREAD

**Issue by Darcy220606** [nf-core/funcscan#158]
### Description of feature

deepBGC currently writes the files in parent directory with sample name and within that a subdir again with sample name and within that the output results 
example: `../results/bgc/deepbgc/Sample_1/Sample_1/files+evaluation dir`

**Comment by jfy133** [comment]
Hmmm, I don't get hat exactly:

![image](https://user-images.githubusercontent.com/17950287/205261634-287bb789-7ab0-4d86-aef7-2e5cd6758614.png)

But I see why this is now: 

https://github.com/nf-core/modules/blob/5e34754d42cd2d5d248ca8673c0a53cdf5624905/modules/nf-core/deepbgc/pipeline/main.nf

the module is wrong, it should be updated to `prefix`  rather than `${genome.baseName}/`

@louperelo do you want to look into this or shoud I fix it?

**Comment by louperelo** [comment]
As you already detected the problem, please go on and fix it @jfy133

**Comment by jfy133** [comment]
https://github.com/nf-core/modules/pull/2605
