### ISSUE TITLE
Error with uncompressed FASTA files

### ISSUE THREAD

**Issue by tavareshugo** [nf-core/funcscan#309]
### Description of the bug

When supplying uncompressed FASTA files in the samplesheet, I now get an error: 

```
Fasta file for reads must be provided, cannot contain spaces and must have extension '.fa.gz', '.fna.gz' or '.fasta.gz'
```

I've locally patched it by changing the regular expression in the [schema_input.json](https://github.com/nf-core/funcscan/blob/eb8f79ce5a966f5a01b398dfe7d881c04b697192/assets/schema_input.json#L21): 

```
^\\S+\\.f(ast|n)?a(\\.gz)?$
```

To make `.gz` optional. 

In addition, I believe the current expression doesn't accept `.fas`, which is also sometimes used for FASTA files. 
Perhaps the expression could be changed to: 

```
^\\S+\\.(fasta|fas|fa|fna)(\\.gz)?$
```

**Comment by jfy133** [comment]
Thanks @tavareshugo ! Much of the team is either on parental leave (myself) or at conferences this week, so we might be slow in replying currently! 

The first is definitely a bug (from me, my bad!), if you've already patched it - would you be willing to open a PR?

The second also I agree would be worth supplying, but it would be important to test to make sure all the screening tools  accept this as input (some are fickly with file naming...).

If you had time, would you be able to do this? Otherwise one of us can test once we are back next week :)
