### ISSUE TITLE
Missing Annotation files

### ISSUE THREAD

**Issue by xeniaroda29** [nf-core/funcscan#389]
### Description of the bug

I encountered an issue while running the nf-core/funcscan pipeline, where the expected annotation files (setting Prokka as the annotation tool) were not generated despite the pipeline completing its execution. It only generates the multiQC files:
![Screenshot from 2024-06-27 16-47-21](https://github.com/nf-core/funcscan/assets/174031782/e2dec1a6-ac84-466d-9585-c46a52257007)

Where custom is the custom.config file I created: 
![Screenshot from 2024-06-27 16-49-02](https://github.com/nf-core/funcscan/assets/174031782/74a30dd2-148d-4203-a98b-62a70aa3d5cc)

### Command used and terminal output

```console
nextflow run nf-core/funcscan -r 1.1.0 -profile custom,docker --outdir results/ -c custom.config
```

**Comment by jfy133** [comment]
I believe this is because annotation will not run unless one of the subworkflows are turned on. 

Currently they are all turned off because by default each is set to not run unless you turn it on, and you have just set the same setting in your config. 

I presume you want to run the BGC subworkflow. Si make sure to set `--run_bgc_screening` in your command.

Please also note that setting pipeline settings in the configs are not recommended, rather use a params yaml file (`-params-file`).

**Comment by xeniaroda29** [comment]
@jfy133 Thank you for your guidance. Following your advice, I ensured that the BGC subworkflow is set to run by including `--run_bgc_screening` in my command together with the parameter `--save_annotations` to save the annotations results in the output directory. It worked perfectly!

Thanks again for your help!
